### ISSUE TITLE
Failure to compile in gradle-1.12

### ISSUE THREAD

**Issue by Jaff** [GradleUp/shadow#46]
I fetched the latest from github today and wanted to add this to our project. During bulld, I got this error:
:shadow:compileJava UP-TO-DATE
:shadow:compileGroovy
:shadow:processResources
:shadow:classes
:shadow:jar
:shadow:assemble
:shadow:compileTestJava UP-TO-DATE
:shadow:compileTestGroovy
Download http://jcenter.bintray.com/org/spockframework/spock-core/0.7-groovy-1.8/spock-core-0.7-groovy-1.8.pom
Download http://jcenter.bintray.com/xmlunit/xmlunit/1.3/xmlunit-1.3.pom
Download http://jcenter.bintray.com/org/codehaus/groovy/groovy-all/1.8.8/groovy-all-1.8.8.pom
Download http://jcenter.bintray.com/org/spockframework/spock-core/0.7-groovy-1.8/spock-core-0.7-groovy-1.8.jar
Download http://jcenter.bintray.com/xmlunit/xmlunit/1.3/xmlunit-1.3.jar
Download http://jcenter.bintray.com/org/codehaus/groovy/groovy-all/1.8.8/groovy-all-1.8.8.jar
startup failed:
/home/ccuser/work/MaRS/mars/buildSrc/shadow/src/test/groovy/com/github/jengelman/gradle/plugins/shadow/integ/AppendingTransformerIntegrationSpec.groovy: 36: unable to resolve class org.gradle.tooling.internal.consumer.parameters.ConsumerConnectionParameters
 @ line 36, column 1.
   import org.gradle.tooling.internal.consumer.parameters.ConsumerConnectionParameters
   ^

1 error

:shadow:compileTestGroovy FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':shadow:compileTestGroovy'.
  > Compilation failed; see the compiler error output for details.
