### ISSUE TITLE
Relocate no longer works as of 9.3.0

### ISSUE THREAD

**Issue by NonSwag** [GradleUp/shadow#1894]
### Expected and Results

Relocate should still work in 9.3.0 but throws an error

`Caused by: java.lang.NoSuchMethodError: 'void org.objectweb.asm.commons.Remapper.<init>(int)'`

### Related environment and versions

- gradle 9.4.0-milestone-4
- shadow 9.3.0

### Reproduction steps

1. Add shadow 9.3.0 to your project
2. Relocate a package in `tasks.shadowJar`
3. run `shadowJar`

### Anything else?

https://pastebin.com/BwkBPeRJ

9.2.2 works as expected

**Comment by Goooler** [comment]
I can't reproduce this. Can you link your reproducer?

**Comment by NonSwag** [comment]
https://github.com/faststats-dev/dev-kits/pull/55

**Comment by NonSwag** [comment]
Thanks for the quick fix
